apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-jupyter-testing
spec:
  title: Jupyter Testing
  description: Play area for testing JupyterLab.
  url: https://github.com/jupyter-on-kubernetes/lab-jupyter-testing
  content:
    image: jupyter-environment:*
    files: github.com/jupyter-on-kubernetes/lab-jupyter-testing
  duration: 60m
  session:
    budget: x-small
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
        plugins:
          enabled: true
    resources:
      memory: 1Gi
      storage: 5Gi
